### ISSUE TITLE
ESX, Use Item

### ISSUE THREAD

**Issue by RickvanO** [DiscworldZA/disc-inventoryhud#2]
Using a item is not possible

**Comment by Yozz001** [comment]
having the exact same problem

**Comment by DiscworldZA** [comment]
Did you guys register it for use with my inventory?

**Comment by Maayk** [comment]
I am also having the same problem, use the item and get a giant console error 
`
TriggerEvent('disc-inventoryhud:registerItemUse',"bread", function(source, item)
	local xPlayer = ESX.GetPlayerFromId(source)
	print(source)

	TriggerEvent('disc-inventoryhud:removeItem', source, item.Id, 1, item.Slot)

	TriggerClientEvent('esx_status:add', source, 'hunger', 200000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('rplay-basic:notification',source,'success','Você comeu 1 pão',2500)
end)
`
the error: 

https://prnt.sc/qhdp94

**Comment by RickvanO** [comment]
> Did you guys register it for use with my inventory?

No I didn't. So I have to integrate everything? Could you could tell me in short how to make everything working with esx? If I made everything working I will make a guide that you can copy paste into a README file :)

**Comment by DiscworldZA** [comment]
Nah, Rex is making one, no need. He already has a fork with most things working
