### ISSUE TITLE
Error starting server

### ISSUE THREAD

**Issue by Revel1990** [DiscworldZA/disc-inventoryhud#3]
Error i get when starting the server:

```
Creating script environments for disc-inventoryhud
Instantiated instance of script disc_inventoryhud_server.Main.
Instantiated instance of script disc_inventoryhud_server.MySQL.MySQLHandler.
SCRIPT ERROR in call ref: TypeError: Cannot read property 'execute' of null

> callback (@mysql-async/mysql-async.js:4936)
> void disc_inventoryhud_server.MySQL.MySQLHandler.FetchAll(string query, Dictionary<string, object> pars, Action<List<object>> action) (@disc-inventoryhud/disc_inventoryhud_server.net.dll:0)
> void disc_inventoryhud_server.Inventory.Drop.LoadDrops() (@disc-inventoryhud/disc_inventoryhud_server.net.dll:0)
> new disc_inventoryhud_server.Inventory.Drop() (@disc-inventoryhud/disc_inventoryhud_server.net.dll:0)
```

**Comment by DayZen16** [comment]
Having the same issue. Are you on a linux server also?

**Comment by JEStudios** [comment]
![image](https://user-images.githubusercontent.com/6571481/71354356-ad62e000-2549-11ea-9c6e-d58aeb683588.png)

Same error but windows based server

**Comment by DonDanGG** [comment]
Same - windows based

**Comment by MindFrags** [comment]
I have noticed that the SQL file uses esx_essentialmode rather than just straight essentialmode. 

I edited my SQL file accordingly prior to injection, and haven't had this error appear.

**Comment by DonDanGG** [comment]
Not the case for me, i've noticed that from the start as my database name is different and changed it before importing the sql

**Comment by DiscworldZA** [comment]
Should be fixed now. Loaded Drops when Sql was not ready
