### ISSUE TITLE
Error Starting Server 

### ISSUE THREAD

**Issue by JEStudios** [DiscworldZA/disc-inventoryhud#4]
![image](https://user-images.githubusercontent.com/6571481/71496442-5303a100-2821-11ea-9618-53b5075d7eb5.png)
 Using latest version ...

**Comment by DayZen16** [comment]
Still have the same issue also when updated to the latest version.

**Comment by Revel1990** [comment]
I believe he forgot to update the code on github after he told us he fixed it. so be patience :)

**Comment by JEStudios** [comment]
oh Im patient just reporting ;)

**Comment by DiscworldZA** [comment]
This should not occur anymore, was due to loading itemdata before mysql was ready
